### ISSUE TITLE
Hello world example does not print hello world

### ISSUE THREAD

**Issue by AndrewSav** [Codesmith1024/Minimum#1]
It appears that [Hello World](https://github.com/Codesmith1024/Minimum/blob/master/examples/hello.txt) program does not print hello world:

```
D:\Users\andrewsav\Documents\GitHub\Minimum\src\Release>Minimal-2D.exe
E`bbe,*world


Program Execution Complete.
782 Instructions Processed.
```
Any idea what went wrong?

Note, that [this](https://esolangs.org/wiki/User:Marinus/Minimal-2D_interpreter) works as expected for the same hello world program

**Comment by Codesmith1024** [comment]
I'll have to take a look at it!

**Comment by Codesmith1024** [comment]
Haha I was originally skipping NOPs implicitly, so the skip operation skipped the next 'real' instruction.

c676f570fc03da85107884e8d3c9d03b93221b90 fixes the hello world for me.

Let me know if it's still giving you issues, or if I can close it.

**Comment by AndrewSav** [comment]
Close it if you do not hear from me in the next 48 hours. I'll try to test it and get back to you before than. Thank you for your work!

**Comment by AndrewSav** [comment]
Looks good, closing.
